name: v0.3.1-typescript

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: unzip # no longer builds -- unzip prebuilt archive
      run: |
        set -x -e
        unzip 0.3.1.zip
        ls -la /home/runner/work/fluid/fluid/0.3.1/
    - name: gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: 0.3.1/
        destination_dir: 0.3.1/
